### ISSUE TITLE
Create an onboarding page

### ISSUE THREAD

**Issue by 0x1026** [Projecte-UrbanTree/UrbanTree#151]
## Tasks
- [ ] Possibility to create an admin user.
- [ ] Database migration step.
- [ ] Database seeding step.
