### ISSUE TITLE
Implement and Standardize Code Commenting Guidelines

### ISSUE THREAD

**Issue by 0x1026** [Projecte-UrbanTree/UrbanTree#156]
Effective commenting is essential for maintaining clarity and collaboration in the project. This issue focuses on adding consistent, meaningful comments to the codebase and establishing guidelines for future development.  

## Tasks
- [ ] **Establish Commenting Guidelines**  
   - Define a standard style for comments, including:  
     - File headers.  
     - Function/method documentation using tools like PHPDoc.  
     - Inline comments for non-obvious or complex logic.  
     - Section comments to organize code blocks.  
   - Document the commenting standards in a shared guideline for team use.
- [ ] **Add Comments to Existing Code**  
   - Review the codebase to:  
     - Add file header comments explaining the file's purpose and authorship.  
     - Document functions and methods with clear explanations of inputs, outputs, and logic.  
     - Add inline comments for complex logic and critical decisions.  
   - Ensure all comments are clear, concise, and reflect the current state of the code.  
- [ ] **Validate Comments**  
   - Review the comments to ensure they:  
     - Are meaningful and not redundant.  
     - Use proper grammar and spelling.  
     - Follow the agreed-upon standards.  
- [ ] **Integrate Commenting into Development Workflow**  
   - Include a step in code reviews to check for proper commenting.  
   - Encourage developers to update comments whenever code is modified.  

### File Header Comment
  ```php  
  /*  
   * File: user_auth.php  
   * Description: Handles user authentication processes.  
   * Author: Class A  
   * Date: November 2024  
   */  
  ```  

### Function Documentation
  ```php  
  /**  
   * Sends a welcome email to a new user.  
   *  
   * @param string $email The user's email address.  
   * @return bool True if the email was sent successfully.  
   */  
  function sendWelcomeEmail($email) {  
      // Logic here  
  }  
  ```  

### Section Header Comment
  ```php  
  // ==========================  
  // User Authentication Logic  
  // ==========================  
  ```  

## Considerations  
- Avoid over-commenting or redundant comments that merely repeat what the code does.  
- Ensure comments are updated whenever related code is changed.  
- Use comments to explain *why* the code exists, not just *what* it does (unless the logic is complex).
